[2021-07-20 17:04:13,486] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:02:00+00:00 [queued]>
[2021-07-20 17:04:13,504] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:02:00+00:00 [queued]>
[2021-07-20 17:04:13,504] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:04:13,504] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:04:13,504] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:04:13,720] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse2> on 2021-07-19T00:02:00+00:00
[2021-07-20 17:04:13,725] {standard_task_runner.py:52} INFO - Started process 415266 to run task
[2021-07-20 17:04:13,738] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse2', '2021-07-19T00:02:00+00:00', '--job-id', '283', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpv8rmi4ow', '--error-file', '/tmp/tmp_3a2dg3d']
[2021-07-20 17:04:13,740] {standard_task_runner.py:77} INFO - Job 283: Subtask fuse2
[2021-07-20 17:04:14,657] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse2 2021-07-19T00:02:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:04:17,492] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse2
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:02:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:02:00+00:00
[2021-07-20 17:04:28,984] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:04:28,990] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse2, execution_date=20210719T000200, start_date=20210720T111913, end_date=20210720T111928
[2021-07-20 17:04:29,343] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:04:29,374] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:01:30,788] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:02:00+00:00 [queued]>
[2021-07-20 18:01:30,985] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:02:00+00:00 [queued]>
[2021-07-20 18:01:30,986] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:01:30,986] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:01:30,986] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:01:31,059] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse2> on 2021-07-19T00:02:00+00:00
[2021-07-20 18:01:31,064] {standard_task_runner.py:52} INFO - Started process 542881 to run task
[2021-07-20 18:01:31,078] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse2', '2021-07-19T00:02:00+00:00', '--job-id', '283', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpwujy2ck4', '--error-file', '/tmp/tmpadz_a5nf']
[2021-07-20 18:01:31,080] {standard_task_runner.py:77} INFO - Job 283: Subtask fuse2
[2021-07-20 18:01:31,205] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse2 2021-07-19T00:02:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:01:31,387] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse2
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:02:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:02:00+00:00
[2021-07-20 18:01:39,865] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:01:39,873] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse2, execution_date=20210719T000200, start_date=20210720T121630, end_date=20210720T121639
[2021-07-20 18:01:39,968] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:01:40,007] {local_task_job.py:151} INFO - Task exited with return code 0
