[2021-07-20 19:48:04,266] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:08:00+00:00 [queued]>
[2021-07-20 19:48:04,276] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:08:00+00:00 [queued]>
[2021-07-20 19:48:04,276] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:48:04,276] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 19:48:04,276] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:48:04,353] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse2> on 2021-07-19T00:08:00+00:00
[2021-07-20 19:48:04,357] {standard_task_runner.py:52} INFO - Started process 1037782 to run task
[2021-07-20 19:48:04,368] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse2', '2021-07-19T00:08:00+00:00', '--job-id', '322', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9oe8yuh2', '--error-file', '/tmp/tmp766wb09w']
[2021-07-20 19:48:04,369] {standard_task_runner.py:77} INFO - Job 322: Subtask fuse2
[2021-07-20 19:48:05,578] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse2 2021-07-19T00:08:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 19:48:05,758] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse2
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:08:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:08:00+00:00
[2021-07-20 19:48:13,281] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 19:48:13,286] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse2, execution_date=20210719T000800, start_date=20210720T140304, end_date=20210720T140313
[2021-07-20 19:48:13,390] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 19:48:13,419] {local_task_job.py:151} INFO - Task exited with return code 0
