[2021-07-20 17:08:21,446] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse5 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 17:08:21,458] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse5 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 17:08:21,458] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:08:21,458] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:08:21,458] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:08:21,542] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse5> on 2021-07-19T00:01:00+00:00
[2021-07-20 17:08:21,544] {standard_task_runner.py:52} INFO - Started process 418761 to run task
[2021-07-20 17:08:21,547] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse5', '2021-07-19T00:01:00+00:00', '--job-id', '295', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpcapliiz_', '--error-file', '/tmp/tmpzwjcu7v0']
[2021-07-20 17:08:21,548] {standard_task_runner.py:77} INFO - Job 295: Subtask fuse5
[2021-07-20 17:08:21,657] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse5 2021-07-19T00:01:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:08:21,875] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse5
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:01:00+00:00
[2021-07-20 17:08:25,881] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:08:25,885] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse5, execution_date=20210719T000100, start_date=20210720T112321, end_date=20210720T112325
[2021-07-20 17:08:25,978] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:08:26,014] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:05:14,903] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse5 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 18:05:14,933] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse5 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 18:05:14,933] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:05:14,934] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:05:14,934] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:05:15,013] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse5> on 2021-07-19T00:01:00+00:00
[2021-07-20 18:05:15,017] {standard_task_runner.py:52} INFO - Started process 546403 to run task
[2021-07-20 18:05:15,024] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse5', '2021-07-19T00:01:00+00:00', '--job-id', '295', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp5ulmy2q5', '--error-file', '/tmp/tmp05owz0jo']
[2021-07-20 18:05:15,025] {standard_task_runner.py:77} INFO - Job 295: Subtask fuse5
[2021-07-20 18:05:15,140] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse5 2021-07-19T00:01:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:05:16,226] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse5
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:01:00+00:00
[2021-07-20 18:05:19,524] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:05:19,663] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse5, execution_date=20210719T000100, start_date=20210720T122014, end_date=20210720T122019
[2021-07-20 18:05:20,205] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-07-20 18:05:20,211] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:05:20,215] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 546403
[2021-07-20 18:05:20,215] {process_utils.py:66} INFO - Process psutil.Process(pid=546403, status='terminated', exitcode=0, started='18:05:14') (546403) terminated with exit code 0
