[2021-07-20 17:06:24,349] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 17:06:24,360] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 17:06:24,360] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:06:24,360] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:06:24,361] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:06:24,438] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse4> on 2021-07-19T00:01:00+00:00
[2021-07-20 17:06:24,444] {standard_task_runner.py:52} INFO - Started process 416959 to run task
[2021-07-20 17:06:24,456] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse4', '2021-07-19T00:01:00+00:00', '--job-id', '289', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmphkvz9_2v', '--error-file', '/tmp/tmps7rdlmpi']
[2021-07-20 17:06:24,458] {standard_task_runner.py:77} INFO - Job 289: Subtask fuse4
[2021-07-20 17:06:24,608] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse4 2021-07-19T00:01:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:06:24,853] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse4
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:01:00+00:00
[2021-07-20 17:06:33,909] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:06:33,913] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse4, execution_date=20210719T000100, start_date=20210720T112124, end_date=20210720T112133
[2021-07-20 17:06:34,023] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:06:34,043] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:03:18,444] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 18:03:18,455] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 18:03:18,455] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:03:18,455] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:03:18,455] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:03:18,533] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse4> on 2021-07-19T00:01:00+00:00
[2021-07-20 18:03:18,537] {standard_task_runner.py:52} INFO - Started process 544587 to run task
[2021-07-20 18:03:18,547] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse4', '2021-07-19T00:01:00+00:00', '--job-id', '289', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpi67q2pzi', '--error-file', '/tmp/tmppa_qz9ah']
[2021-07-20 18:03:18,549] {standard_task_runner.py:77} INFO - Job 289: Subtask fuse4
[2021-07-20 18:03:18,974] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse4 2021-07-19T00:01:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:03:19,245] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse4
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:01:00+00:00
[2021-07-20 18:03:28,440] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:03:28,444] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse4, execution_date=20210719T000100, start_date=20210720T121818, end_date=20210720T121828
[2021-07-20 18:03:28,527] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:03:28,540] {local_task_job.py:151} INFO - Task exited with return code 0
