[2021-07-20 19:16:09,452] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:06:00+00:00 [queued]>
[2021-07-20 19:16:09,463] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:06:00+00:00 [queued]>
[2021-07-20 19:16:09,463] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:16:09,463] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 19:16:09,463] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:16:09,539] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse3> on 2021-07-19T00:06:00+00:00
[2021-07-20 19:16:09,543] {standard_task_runner.py:52} INFO - Started process 874529 to run task
[2021-07-20 19:16:09,553] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse3', '2021-07-19T00:06:00+00:00', '--job-id', '314', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp99_reqnw', '--error-file', '/tmp/tmpzkw3qk6o']
[2021-07-20 19:16:09,555] {standard_task_runner.py:77} INFO - Job 314: Subtask fuse3
[2021-07-20 19:16:09,711] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse3 2021-07-19T00:06:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 19:16:09,898] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse3
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:06:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:06:00+00:00
[2021-07-20 19:16:12,951] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 19:16:12,954] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse3, execution_date=20210719T000600, start_date=20210720T133109, end_date=20210720T133112
[2021-07-20 19:16:13,050] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 19:16:13,092] {local_task_job.py:151} INFO - Task exited with return code 0
