[2021-07-20 17:38:52,308] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 17:38:52,319] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 17:38:52,319] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:38:52,319] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:38:52,319] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:38:52,928] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse3> on 2021-07-19T00:05:00+00:00
[2021-07-20 17:38:52,930] {standard_task_runner.py:52} INFO - Started process 534212 to run task
[2021-07-20 17:38:52,934] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse3', '2021-07-19T00:05:00+00:00', '--job-id', '306', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp2tsup5rd', '--error-file', '/tmp/tmpaplfq1i0']
[2021-07-20 17:38:52,935] {standard_task_runner.py:77} INFO - Job 306: Subtask fuse3
[2021-07-20 17:38:53,022] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse3 2021-07-19T00:05:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:38:53,271] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse3
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:05:00+00:00
[2021-07-20 17:38:57,116] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:38:57,119] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse3, execution_date=20210719T000500, start_date=20210720T115352, end_date=20210720T115357
[2021-07-20 17:38:57,259] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:38:57,278] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:39:41,618] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 18:39:41,640] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 18:39:41,640] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:39:41,640] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:39:41,641] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:39:41,728] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse3> on 2021-07-19T00:05:00+00:00
[2021-07-20 18:39:41,733] {standard_task_runner.py:52} INFO - Started process 711015 to run task
[2021-07-20 18:39:41,744] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse3', '2021-07-19T00:05:00+00:00', '--job-id', '306', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp1rpoac49', '--error-file', '/tmp/tmp4upfshi0']
[2021-07-20 18:39:41,746] {standard_task_runner.py:77} INFO - Job 306: Subtask fuse3
[2021-07-20 18:39:41,901] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse3 2021-07-19T00:05:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:39:42,158] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse3
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:05:00+00:00
[2021-07-20 18:39:46,876] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:39:46,882] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse3, execution_date=20210719T000500, start_date=20210720T125441, end_date=20210720T125446
[2021-07-20 18:39:46,996] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:39:47,008] {local_task_job.py:151} INFO - Task exited with return code 0
