[2021-07-20 20:18:32,643] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse10 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 20:18:32,653] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse10 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 20:18:32,654] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 20:18:32,654] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 20:18:32,654] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 20:18:32,729] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse10> on 2021-07-19T00:00:00+00:00
[2021-07-20 20:18:32,731] {standard_task_runner.py:52} INFO - Started process 1200840 to run task
[2021-07-20 20:18:32,736] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse10', '2021-07-19T00:00:00+00:00', '--job-id', '330', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmplqzwebze', '--error-file', '/tmp/tmphmbxfr80']
[2021-07-20 20:18:32,736] {standard_task_runner.py:77} INFO - Job 330: Subtask fuse10
[2021-07-20 20:18:33,434] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse10 2021-07-19T00:00:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 20:18:33,653] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse10
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:00:00+00:00
[2021-07-20 20:18:38,184] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 20:18:38,187] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse10, execution_date=20210719T000000, start_date=20210720T143332, end_date=20210720T143338
[2021-07-20 20:18:38,269] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 20:18:38,325] {local_task_job.py:151} INFO - Task exited with return code 0
