[2021-07-20 17:07:59,716] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:02:00+00:00 [queued]>
[2021-07-20 17:07:59,744] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:02:00+00:00 [queued]>
[2021-07-20 17:07:59,744] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:07:59,744] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:07:59,745] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:07:59,826] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse4> on 2021-07-19T00:02:00+00:00
[2021-07-20 17:07:59,829] {standard_task_runner.py:52} INFO - Started process 418355 to run task
[2021-07-20 17:07:59,834] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse4', '2021-07-19T00:02:00+00:00', '--job-id', '294', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp6oeeg9t_', '--error-file', '/tmp/tmp0mkgc1uq']
[2021-07-20 17:07:59,835] {standard_task_runner.py:77} INFO - Job 294: Subtask fuse4
[2021-07-20 17:07:59,931] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse4 2021-07-19T00:02:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:08:00,946] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse4
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:02:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:02:00+00:00
[2021-07-20 17:08:12,358] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:08:12,362] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse4, execution_date=20210719T000200, start_date=20210720T112259, end_date=20210720T112312
[2021-07-20 17:08:12,487] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:08:12,509] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:04:50,178] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:02:00+00:00 [queued]>
[2021-07-20 18:04:50,201] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:02:00+00:00 [queued]>
[2021-07-20 18:04:50,201] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:04:50,201] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:04:50,201] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:04:52,258] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse4> on 2021-07-19T00:02:00+00:00
[2021-07-20 18:04:52,262] {standard_task_runner.py:52} INFO - Started process 545987 to run task
[2021-07-20 18:04:52,267] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse4', '2021-07-19T00:02:00+00:00', '--job-id', '294', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpl2rv3m5h', '--error-file', '/tmp/tmpcm81ccfi']
[2021-07-20 18:04:52,268] {standard_task_runner.py:77} INFO - Job 294: Subtask fuse4
[2021-07-20 18:04:52,989] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse4 2021-07-19T00:02:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:04:53,507] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse4
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:02:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:02:00+00:00
[2021-07-20 18:05:04,627] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:05:04,632] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse4, execution_date=20210719T000200, start_date=20210720T121950, end_date=20210720T122004
[2021-07-20 18:05:05,177] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:05:05,208] {local_task_job.py:151} INFO - Task exited with return code 0
