[2021-07-20 17:03:29,187] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 17:03:29,206] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 17:03:29,206] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:03:29,206] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:03:29,206] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:03:29,344] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse3> on 2021-07-19T00:00:00+00:00
[2021-07-20 17:03:29,348] {standard_task_runner.py:52} INFO - Started process 414696 to run task
[2021-07-20 17:03:29,360] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse3', '2021-07-19T00:00:00+00:00', '--job-id', '281', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9wggpchp', '--error-file', '/tmp/tmpt21lkamd']
[2021-07-20 17:03:29,361] {standard_task_runner.py:77} INFO - Job 281: Subtask fuse3
[2021-07-20 17:03:29,530] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse3 2021-07-19T00:00:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:03:31,939] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse3
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:00:00+00:00
[2021-07-20 17:03:36,122] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:03:36,126] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse3, execution_date=20210719T000000, start_date=20210720T111829, end_date=20210720T111836
[2021-07-20 17:03:36,331] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:03:36,349] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:00:44,840] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 18:00:44,849] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 18:00:44,849] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:00:44,849] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:00:44,849] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:00:44,921] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse3> on 2021-07-19T00:00:00+00:00
[2021-07-20 18:00:44,926] {standard_task_runner.py:52} INFO - Started process 542297 to run task
[2021-07-20 18:00:44,938] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse3', '2021-07-19T00:00:00+00:00', '--job-id', '281', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpwpt51ev7', '--error-file', '/tmp/tmp8za_ar82']
[2021-07-20 18:00:44,939] {standard_task_runner.py:77} INFO - Job 281: Subtask fuse3
[2021-07-20 18:00:45,061] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse3 2021-07-19T00:00:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:00:45,316] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse3
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:00:00+00:00
[2021-07-20 18:00:48,673] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:00:48,677] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse3, execution_date=20210719T000000, start_date=20210720T121544, end_date=20210720T121548
[2021-07-20 18:00:48,829] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:00:48,839] {local_task_job.py:151} INFO - Task exited with return code 0
