[2021-07-20 17:04:58,654] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 17:04:58,660] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 17:04:58,660] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:04:58,660] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:04:58,660] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:04:59,178] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse4> on 2021-07-19T00:00:00+00:00
[2021-07-20 17:04:59,183] {standard_task_runner.py:52} INFO - Started process 415712 to run task
[2021-07-20 17:04:59,189] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse4', '2021-07-19T00:00:00+00:00', '--job-id', '285', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpgtndycly', '--error-file', '/tmp/tmpyuercxtu']
[2021-07-20 17:04:59,189] {standard_task_runner.py:77} INFO - Job 285: Subtask fuse4
[2021-07-20 17:04:59,301] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse4 2021-07-19T00:00:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:04:59,574] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse4
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:00:00+00:00
[2021-07-20 17:05:07,562] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:05:07,566] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse4, execution_date=20210719T000000, start_date=20210720T111958, end_date=20210720T112007
[2021-07-20 17:05:07,821] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:05:07,850] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:02:02,097] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 18:02:02,117] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 18:02:02,118] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:02:02,118] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:02:02,118] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:02:02,206] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse4> on 2021-07-19T00:00:00+00:00
[2021-07-20 18:02:02,211] {standard_task_runner.py:52} INFO - Started process 543353 to run task
[2021-07-20 18:02:02,222] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse4', '2021-07-19T00:00:00+00:00', '--job-id', '285', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpen85_k3q', '--error-file', '/tmp/tmpwccenyq5']
[2021-07-20 18:02:02,224] {standard_task_runner.py:77} INFO - Job 285: Subtask fuse4
[2021-07-20 18:02:02,344] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse4 2021-07-19T00:00:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:02:02,650] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse4
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:00:00+00:00
[2021-07-20 18:02:13,008] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:02:13,073] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse4, execution_date=20210719T000000, start_date=20210720T121702, end_date=20210720T121713
[2021-07-20 18:02:13,268] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:02:13,298] {local_task_job.py:151} INFO - Task exited with return code 0
