[2021-07-20 19:15:51,540] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:07:00+00:00 [queued]>
[2021-07-20 19:15:51,549] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:07:00+00:00 [queued]>
[2021-07-20 19:15:51,549] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:15:51,549] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 19:15:51,549] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:15:51,769] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse2> on 2021-07-19T00:07:00+00:00
[2021-07-20 19:15:51,773] {standard_task_runner.py:52} INFO - Started process 874251 to run task
[2021-07-20 19:15:51,777] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse2', '2021-07-19T00:07:00+00:00', '--job-id', '313', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmppl56d5_0', '--error-file', '/tmp/tmpbrw7i8eo']
[2021-07-20 19:15:51,777] {standard_task_runner.py:77} INFO - Job 313: Subtask fuse2
[2021-07-20 19:15:52,339] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse2 2021-07-19T00:07:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 19:15:53,675] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse2
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:07:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:07:00+00:00
[2021-07-20 19:16:01,737] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 19:16:01,744] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse2, execution_date=20210719T000700, start_date=20210720T133051, end_date=20210720T133101
[2021-07-20 19:16:01,853] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 19:16:01,860] {local_task_job.py:151} INFO - Task exited with return code 0
