[2021-07-20 17:39:06,955] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 17:39:06,975] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 17:39:06,976] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:39:06,976] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:39:06,976] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:39:07,055] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse4> on 2021-07-19T00:04:00+00:00
[2021-07-20 17:39:07,057] {standard_task_runner.py:52} INFO - Started process 534475 to run task
[2021-07-20 17:39:07,062] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse4', '2021-07-19T00:04:00+00:00', '--job-id', '307', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpin0l35sc', '--error-file', '/tmp/tmpgj_uj15i']
[2021-07-20 17:39:07,063] {standard_task_runner.py:77} INFO - Job 307: Subtask fuse4
[2021-07-20 17:39:07,221] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse4 2021-07-19T00:04:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:39:07,675] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse4
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:04:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:04:00+00:00
[2021-07-20 17:39:17,783] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:39:17,786] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse4, execution_date=20210719T000400, start_date=20210720T115406, end_date=20210720T115417
[2021-07-20 17:39:17,933] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:39:17,973] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:39:56,746] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 18:39:56,757] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse4 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 18:39:56,758] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:39:56,758] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:39:56,758] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:39:56,865] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse4> on 2021-07-19T00:04:00+00:00
[2021-07-20 18:39:56,870] {standard_task_runner.py:52} INFO - Started process 711193 to run task
[2021-07-20 18:39:56,882] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse4', '2021-07-19T00:04:00+00:00', '--job-id', '307', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp88yp6low', '--error-file', '/tmp/tmpt9l219oa']
[2021-07-20 18:39:56,883] {standard_task_runner.py:77} INFO - Job 307: Subtask fuse4
[2021-07-20 18:39:57,199] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse4 2021-07-19T00:04:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:39:58,416] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse4
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:04:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:04:00+00:00
[2021-07-20 18:40:12,543] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:40:12,551] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse4, execution_date=20210719T000400, start_date=20210720T125456, end_date=20210720T125512
[2021-07-20 18:40:12,648] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:40:12,687] {local_task_job.py:151} INFO - Task exited with return code 0
