[2021-07-20 17:04:38,931] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 17:04:38,941] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 17:04:38,941] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:04:38,941] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:04:38,941] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:04:39,011] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse3> on 2021-07-19T00:01:00+00:00
[2021-07-20 17:04:39,014] {standard_task_runner.py:52} INFO - Started process 415545 to run task
[2021-07-20 17:04:39,022] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse3', '2021-07-19T00:01:00+00:00', '--job-id', '284', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpfxa2tnlu', '--error-file', '/tmp/tmpoyrxzgy9']
[2021-07-20 17:04:39,024] {standard_task_runner.py:77} INFO - Job 284: Subtask fuse3
[2021-07-20 17:04:40,205] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse3 2021-07-19T00:01:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:04:41,584] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse3
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:01:00+00:00
[2021-07-20 17:04:47,192] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:04:47,195] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse3, execution_date=20210719T000100, start_date=20210720T111938, end_date=20210720T111947
[2021-07-20 17:04:47,278] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:04:47,282] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:01:48,482] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 18:01:48,493] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 18:01:48,493] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:01:48,493] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:01:48,493] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:01:48,605] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse3> on 2021-07-19T00:01:00+00:00
[2021-07-20 18:01:48,610] {standard_task_runner.py:52} INFO - Started process 543158 to run task
[2021-07-20 18:01:48,624] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse3', '2021-07-19T00:01:00+00:00', '--job-id', '284', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxqjy4im1', '--error-file', '/tmp/tmpp0eoy8if']
[2021-07-20 18:01:48,625] {standard_task_runner.py:77} INFO - Job 284: Subtask fuse3
[2021-07-20 18:01:48,960] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse3 2021-07-19T00:01:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:01:49,667] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse3
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:01:00+00:00
[2021-07-20 18:01:53,711] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:01:53,716] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse3, execution_date=20210719T000100, start_date=20210720T121648, end_date=20210720T121653
[2021-07-20 18:01:53,806] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:01:53,836] {local_task_job.py:151} INFO - Task exited with return code 0
